### ISSUE TITLE
Upgrade Postgres and start passing CancellationToken to PrepareAsync() if issue is resolved

### ISSUE THREAD

**Issue by madelson** [madelson/DistributedLock#111]
See https://github.com/npgsql/npgsql/issues/4209

**Comment by M4urici0GM** [comment]
Isnt this closed with postgre;'s [#4559](https://github.com/npgsql/npgsql/pull/4559) ?

**Comment by madelson** [comment]
@M4urici0GM seems like it is, so this issue can be addressed in the next release of the postgres DistributedLock lib.

**Comment by Bartleby2718** [comment]
@madelson Given the latest comment, I think we'll need a major version bump for `npgsql`. 

[The breaking changes introduced in npgsql major version 6](https://www.npgsql.org/doc/release-notes/6.0.html#breaking-changes) doesn't seem to affect this library, but will this affect consumers?

**Comment by madelson** [comment]
@Bartleby2718 I agree; I think we'd go all the way to 8.x.
