### ISSUE TITLE
Doc of Redis

### ISSUE THREAD

**Issue by RyanOvO** [madelson/DistributedLock#124]
Can the documentation for distributed Redis locks be more detailed?
Does Redis implement something similar to a watchdog used to increase the validity of locks that are about to expire but have not been released?
Thanks Very Much!!!!!!

**Comment by madelson** [comment]
Happy to answer any specific questions. I think the overall docs for RedLock (linked from the docs) are a good place to start if you want to understand how the algorithm works at a low level.
