### ISSUE TITLE
Timeout exceeded when trying to acquire the lock

### ISSUE THREAD

**Issue by Wx19880221** [madelson/DistributedLock#139]
Hi 
  when I use 10 threads testing to get distribute lock. There occur error :Timeout exceeded when trying to acquire the lock.
![1659921923889](https://user-images.githubusercontent.com/13740935/183321008-28a995ad-f5f6-4bde-a72a-573fd0e7437e.png)
I set timeout values to 
![1659921974099](https://user-images.githubusercontent.com/13740935/183321070-12bdba72-f76c-4095-acf5-8460ad590ef4.png)

**Comment by madelson** [comment]
@Wx19880221 thanks for your interest in the library!

I see that your timeout is only `6000000` *ticks* which is 0.6s which is pretty short Is it possible that with 10 threads doing various actions you are timing out legitimately? Perhaps you meant to do `TimeSpan.FromSeconds` or `TimeSpan.FromMilliseconds`?

**Comment by Wx19880221** [comment]
Thanks a lot
