### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [madelson/DistributedLock#170]
Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/distributedlock/api/Medallion.Threading.SqlServer.SqlDistributedLock.html
This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/distributedlock/api/Medallion.Threading.SqlServer.SqlDistributedLock.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/distributedlock/api/Medallion.Threading.SqlServer.SqlDistributedLock.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Hope You will find RobiniaDocs useful for this and other projects

Regards
NeuroXiq

**Comment by madelson** [comment]
Thanks for sharing @NeuroXiq this looks interesting. I've looked into docs generators in the past but always found them lacking in some way.

Some questions about Robinia:
* Will there ever be ads or monetization on the robinia site?
* Do I have to do anything to keep the Robinia docs up to date as I publish new library versions?
* Does Robinia offer any way for viewers to see docs versions associated with previous releases?
* The "articles" tab is empty and kind of confusing. Is there any way to hide that or have it link to my existing docs pages in github?

**Comment by madelson** [comment]
@NeuroXiq any updates here?

**Comment by NeuroXiq** [comment]
Thanks for response,
short answer to questions:
1. Probably Yes
2. No
3. No - this is TODO
4. No  - this is TODO
- - - -
Long answers:
1.  Its depends how things will go on. For now there is no any ads and I need to pay myself for hosting (x509 Cert , Domain Name, VPS etc.). I will be very happy if I don't need to pay for hosting from my private budget - for example from sponsors or something like that. If . Not sure what You had in mind about this question but if You mean that:
   App will have ads everywhere and any button click/navigation will cause full-screen ad - I definitely do not plan to do something like this, max one ad on the bottom or something like that. 
Best option for me will be without ads but I will see how things go on.

2. This project going to work in a following way:
  1. Login to app
  2. Create project
  3. Insert link in README.md on github of docs
  4. Forgot about this - system will automatically from time to time fetch newest nuget packages and .md docs and rebuild project.
  
So there is no need to maintain anything after creating a project (and project url does not change as well, so no need to updated README.md on github after system auto-rebuild project)

3. I need to implement something better, but for now multiple projects can be created and in cumbersome way to do this
is for example create separate project (manually) for each version.

I need to this about how to do this, when new version was released? How to distinguish what should be hosted and what not?
Example problems: 
 1. Update 'example-doc.md' file and commit&push
 2. Ten minutes later 'update .md' file and  commit&push
 3. Ten minutes later 'update .md' file and  commit&push

So system should create 3 separate versions for each commit? And some other problems. This is my problem how to implement
this but I near future I plan to implement versioning (Maybe tag-based of branch? - but this is my future problem)

4. I need to fix this
- - - -

Right now I'm just looking if anybody is interested in this kind of project - I think it can be very useful because there is no 
effort of hosing API explorer online. Additionaly I can implement what I want, I looking what people expect from the system and progressively I will implement next features :) So what system offer is what I implement. If app does not offer something now I can make it in later versions in the future (if this features looks usefull)

Regards
NeuroXiq

**Comment by madelson** [comment]
@NeuroXiq thanks for the detailed response.

Re: 1 I don’t begrudge you wanting to advertise a bit; just didn’t want to have my project associated with a site serving up aggressive or objectionable ads. Sounds like we’re good here.

I’m definitely interested in this project and I think other library authors will find it useful as well. I’ve tried out a few docs generator tools with the idea that I could host the docs out of the repo itself but all of the ones I tried have issues. The idea that this is “effortless” is very appealing. I plan to try integrating this soon (may be a few weeks since I’m busy atm)!

**Comment by madelson** [comment]
TODO upload nuget packages here: https://dndocs.com/project/create-project

**Comment by NeuroXiq** [comment]
Hello!
Is there any problem with creating a project? If yes could You please try to use incognito in browser and try to signin and check again? :)

**Comment by madelson** [comment]
@NeuroXiq I've been swamped and haven't gotten a chance to try again. Still planning to do this. Will try incognito.

**Comment by madelson** [comment]
@NeuroXiq I'm trying to create a project for DistributedLock but I can't create it because the name is already taken (I think you had created it). That means I can't edit the configuration. Is there any way you can pass ownership of that project to me?

**Comment by NeuroXiq** [comment]
Hi!
Sorry for no respond. Nice to see API docs in README.md file :)

But I would have to ask You about do one change to README.md
This is not correct: https://github.com/NeuroXiq/RobiniaDocs
This URL is not correct: www.robiniadocs.com/...

This is correct: https://github.com/NeuroXiq/DNDocs
This URL is correct: https://dndocs.com/

I created Pull Request with this changes:
https://github.com/madelson/DistributedLock/pull/206/files
You can merge this/delete this pull request and do it on Your own but this must be done

**Please do this as soon as possible because domain www.robiniadocs.com will be delete permamently**

Additionally; I pass ownership to project as suggested.

I think that's all about API docs for now from my side :)
If You have any trouble with this/found any bugs feel free to report everything on https://github.com/NeuroXiq/DNDocs in issues tab, in free time I will try to updated/fix any issues or bugs found

Have a nice day!
Regards
NeuroXiq
