### ISSUE TITLE
How to dispose SqlDistributedLock asynchronously?

### ISSUE THREAD

**Issue by clement911** [madelson/DistributedLock#20]
The `using` pattern is nice and reads very well.

However, the implicit call to Dispose is doing a synchronous db call and blocking the calling thread so I'd love to see an option to dispose asynchronously, even if it means I can't use the `using` keyword in my calling code.

I guess `SqlDistributedLock .TryAcquireAsync` could return an interface like this:

```
IAsyncDisposable : IDisposable
{
    Task DisposeAsync();
}
```

What do you think?

**Comment by madelson** [comment]
Hi @clement911 thanks for the suggestion. I agree that this is a good idea. A few thoughts:

* Changing this would be a binary breaking change, so we would have to do it as part of a 2.0 release
* It looks like .NET Core is working on a standard IAsyncDisposable interface for this (https://github.com/dotnet/corefx/issues/32640), so I would want to wait for that to be released and understand the implications of it (e .g. can you use it in a using block?) before building this.
* Finally, some lock releases can't benefit from async (e. g. transaction-based locks release with SqlTransaction.Dispose(), which isn't async. That said, (a) maybe this will change when IAsyncDisposable comes out and (b) it doesn't stop us from implementing the interface for the cases where we will get the benefit.

**Comment by clement911** [comment]
Makes sense. Looking forward to IAsyncDisposable!
