### ISSUE TITLE
Add additional TFM so the dependency on System.Threading.AccessControl can be removed

### ISSUE THREAD

**Issue by thompson-tomo** [madelson/DistributedLock#204]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
The System.Threading.AccessControl package becomes conditional so only added for the older frameworks

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by madelson** [comment]
@thompson-tomo would it be helpful to you if we offered net8 build without the dependency?

**Comment by thompson-tomo** [comment]
@madelson yes, not sure why I closed this issue.
