### ISSUE TITLE
Dependency on Microsoft.Data.SqlClient 5.2.0 may be unnecessary

### ISSUE THREAD

**Issue by gliljas** [madelson/DistributedLock#210]
Wasn't sure whether to file this issue at all, but at least for your consideration.

I had to do a version rollback today, since Microsoft.Data.SqlClient 5.2.0 is buggy and has a pending hotfix. DistributedLock.SqlServer doesn't really need that version, so the Nuget dependency becomes a bit limiting.

**Comment by madelson** [comment]
@gliljas looks like 5.2.1 is out. Does that work for you?

**Comment by madelson** [comment]
@gliljas for now I published a new version with 5.2.1; if that's still causing problems for you please create a new issue

**Comment by madelson** [comment]
@mapaille is 5.2.* is still causing issues, I'd happily accept a PR to downgrade to 5.1.5
