### ISSUE TITLE
Question: Integration testing competing consumers howto

### ISSUE THREAD

**Issue by stephenpatten** [madelson/DistributedLock#23]
@madelson It's me again.

Wondering how you might be able to use say, VS 2017 with xUnit to create a multiple consumers who will all try and grab a sqlDistributed lock?  This [question](https://github.com/madelson/DistributedLock/issues/21) has some very good advice in it from you, and I'm not opposed to running up LocalDB/SqlExpress, or even reaching out to our development instance. 

The behavior that I saw when I tried to do a naive test where everything was contained in the Fixture and Test was that the locking code in the ctor of the Fixture blocked and the actual test never executed... or something like that..

With xUnit  you can use a fixture to ensure setup and tear-down via the Constructor and Dispose signatures. In the constructor is where I grabbed the lock,  and then wanted to verify in the test method if I could grab the handle and it was real or null. 

So what I'm doing right now is running up a console app that acquires the lock and sleeps in the using statement, then I can run up the unit test and try to get the lock too. This has started yielding results and making me more aware of the behavioral differences between Acquire(timeout) and TryAcquire(timeout) . 

Maybe I should also explain my use case, which is only one consumer can grab the lock while others are blocked. All the clients of said code are using Polly Retry  Policies, in particular retries with back-off and TimeoutException support.

    `    
        private IDisposable GetLockInternal(string key, TimeSpan timeout)
        {
            /* Safe(r) by default... but someone can still abuse this if they want too */
            if (timeout <= default(TimeSpan) || timeout > this.DefaultTimeout)
            {
                timeout = this.DefaultTimeout;
            }

            string safeLockName = SqlDistributedLock.GetSafeLockName(key);
            SqlDistributedLock sqlLock = new SqlDistributedLock(safeLockName, this.config.AWDConnectionString);
            
            /*var handle = sqlLock.TryAcquire(timeout); // Does not enforce timeout */
            var handle = sqlLock.Acquire(timeout);

            if (handle != null)
            {
                try
                {
                    /* Just in case we do want to run some other business logic */
                    if (this.EnsureLock())
                    {
                        return handle;
                    }
                }
                catch
                {
                    handle.Dispose(); // clean up
                    /*throw;*/ // propagate the biz logic error?
                }
            }

            // result is neg
            if (handle != null) 
            {
                handle.Dispose(); // clean up
            }

            return null;
        }
`

Comments and or suggestions are truly welcome if you find the time.

Thank you,
Stephen

**Comment by madelson** [comment]
Hi @stephenpatten thanks for posting. I'm not sure I completely follow what you are trying to achieve and where you are getting stuck. Is the code snippet the code being tested or the code in the test itself? If you can refine down to a small complete example that would help me a lot. Some other thoughts:

> Wondering how you might be able to use say, VS 2017 with xUnit to create a multiple consumers who will all try and grab a sqlDistributed lock?

Connection-string based locks are not re-entrant, so if your goal is to test by simulating a situation with multiple contenders for the lock it should be really simple. One option would be to launch multiple threads with `Task.Run()` or `Parallel.ForEach` and have them all try to use it. If you want something even more direct, you can use a single thread:

```
var @lock = new SqlDistributedLock(...);
using (var handle = @lock.Acquire())
{
    // code that runs in here that tries to take the lock will block
}
```

> I'm not opposed to running up LocalDB/SqlExpress...

I do all my tests against SqlExpress, which is very easy. Really any database should work, although if you use a shared database then you can hit issues if multiple people are running the same test at the same time (this can be worked around by randomizing the lock name used by the test).

> /*var handle = sqlLock.TryAcquire(timeout); // Does not enforce timeout */

I was surprised to see this. The intended behavior is that Acquire(timeout) throws after the timeout expires and TryAcquire(timeout) returns null after the timeout expires. Thus Acquire() with no timeout is like having an infinite timeout while TryAcquire() with no timeout is like having a timeout of zero. What behavior were you seeing?

**Comment by stephenpatten** [comment]
Yeah, I owe you a better question, closing this for the time being.
