### ISSUE TITLE
Explore file-based locking

### ISSUE THREAD

**Issue by madelson** [madelson/DistributedLock#28]
On linux, we can do blocking flock with this method (https://stackoverflow.com/questions/40710549/is-there-a-portable-way-to-put-a-timeout-on-flock) for cancellation.

On windows, we can use LockFileEx in async mode and possibly combine that with cancelioex to cancel the async io operation (not sure if this works). Also since we're doing async IO it's probably not the end of the world to just leave the async task running and have it unlock itself upon completion.

**Comment by c0shea** [comment]
[https://mvolo.com/fun-with-file-locking/](Fun with file locking)

**Comment by madelson** [comment]
@c0shea feel free to check out the new implementation here: https://github.com/madelson/DistributedLock/blob/release-2.0/DistributedLock.FileSystem/FileDistributedLock.cs#L66. If you're interested in trying this out I can publish a prerelease. Otherwise, this will come out with 2.0.
