### ISSUE TITLE
Lock management across services

### ISSUE THREAD

**Issue by Vaccano** [madelson/DistributedLock#40]
I have a scenario where Service A will need to take out a lock on "124578".

Then, 20ish seconds later Service B will get a notification that the lock can be cleared.

Can Service B clear the lock?

From what I am seeing, the lock must be taken and released in the same "instance" (inside a `using` block preferably).

**Is there a way for one system to take the lock and another to release it?**

Update With Full Scenario:

Just in case it is useful, here is the steps to my scenario:

1. Service A gets a notification to create a Container on order 124578.
2. Service A takes out a lock on order 124578 
3. Service A sends out a message to an external system to create the container.  This can take 15 seconds.
4. The message processing system (Service B) gets a message saying that the container was created.
5. Service B clears the lock.
6. Other containers can now be made on order 124578.

**Comment by Vaccano** [comment]
After thinking about this, it would only be possible by having tables saved on the SQL Server instance.

I think I will have to "roll my own" on this one.

**Comment by madelson** [comment]
@Vaccano you *could* do this by having Service B issue a KILL command for the lock-holding SPID, but I don't recommend that approach.

Probably the easiest way to do this would be to have a "completed" column on your order table:

1. Service A gets a notification to create a Container on order 124578.
2. Service A takes out a lock on order 124578
3a. Service A sends out a message to an external system to create the container. This can take 15 seconds.
3b. Service A starts polling to check when the order is completed; at this point it will release the lock
4. The message processing system (Service B) gets a message saying that the container was created.
5. Service B marks the order as completed
6. Other containers can now be made on order 124578.
