### ISSUE TITLE
2.0 Release Miscellaneous tasks

### ISSUE THREAD

**Issue by madelson** [madelson/DistributedLock#44]
Solution restructuring:
- [x] remove old target frameworks
- [x] remove System.Data.SqlClient
- [x] separate out System locks and rename to EventHandle or similar
- [x] separate out SqlLocks
- [x] separate out Core
- [x] set up DistributedLock umbrella package

Things to revisit
- [x] efficient sync-over-async using ValueTask and flowing context through AsyncLocal
- [x] safe naming by default
- [x] remove any obsolete APIs
- [x] look at https://github.com/dotnet/SqlClient/issues/663
- [x] use latest Microsoft.Data.SqlClient (1.1.1 or 2.0)
- [x] namespace audit (add test)
- [x] add test that checks for sealed
- [x] clean up namespaces in tests
- [x] waithandles semaphore
- [x] waithandle permissioning: https://stackoverflow.com/questions/1784392/my-eventwaithandle-says-access-to-the-path-is-denied-but-its-not
- [x] API review test: check static APIs like GetName/MaxNameLength, check that IInternal APIs are explicitly implemented, etc
- [x] ConfigureAwait(false) review test
- [x] review all try-finally's and disposes for ordering issues
- [x] revisit handles nulling things out. Use RefBox where needed
- [x] consider getting rid of reentrancy for everything (e. g. by checking the type)
- [x] after cancellation of SQL lock, do a release to avoid races
- [x] look into CI tests
- ~~[ ] add tests for presence of TransactionScope (Transaction.Current). In particular Postgres's transaction detection to avoid statement_timeout leaks and Multiplexing (what happens if the shared connection gets caught up in multiple transactions?). Seems like in Postgres this is a [connection string option](https://github.com/npgsql/npgsql/blob/b600e5ec36e5aaac87203e78feb2cb4acdba1bca/src/Npgsql/NpgsqlConnection.cs#L233)~~
- [x] update third-party dependencies to latest versions (need to consider https://github.com/npgsql/npgsql/issues/3443 and https://github.com/npgsql/npgsql/issues/3442)
- [x] review for places to use SafeTaskCreate
- [x] revisit cases where public API idempotent disposal doesn't block on the second call
- [x] Add test for lingering console usages
- [x] interpackage dependency version bounds

Final steps:
- [x] resolve all in-code todos
- [x] all tests passing (release mode)
- [x] update docs
- [x] FileSystem docs
- [x] Postgres docs
- [x] Redis docs
- [x] SqlServer docs
- [x] WaitHandles docs
- [x] Locks docs
- [x] Other topics docs
- [x] Reader-writer locks docs
- [x] Semahpores docs
- [x] update release notes
- [x] update versions
- [x] all issues closed
- [x] publish!

**Comment by hoerup** [comment]
Please dont take this the wrong way, I don't want to put any pressure on you - but do you have a plan / roadmap for when 2.0 will be released ?

**Comment by madelson** [comment]
@hoerup I am hoping to release in January 2021; I had to step away from the project for a bit but I am now actively able to work on it again. You can see the issues involved in the release here: https://github.com/madelson/DistributedLock/milestone/1 (just because it isn't closed doesn't mean the work hasn't completed).

**Comment by madelson** [comment]
@hoerup the stable package versions are published.
