### ISSUE TITLE
Consider adding Oracle support

### ISSUE THREAD

**Issue by madelson** [madelson/DistributedLock#45]
Requested by user via nuget.org

Some promising stuff here: https://stackoverflow.com/questions/2627609/is-there-an-equivalent-to-sp-getapplock-sp-releaseapplock-in-oracle

Oracle has a free version for testing here: https://www.oracle.com/database/technologies/appdev/xe.html

**Comment by madelson** [comment]
May be easier after https://github.com/appveyor/ci/issues/31

**Comment by madelson** [comment]
Ok I think I have a basic local setup working:

Container start command:
```
docker run --name oracle-distributed-lock -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=???? oracle/database:18.4.0-xe
```

C# snippet:
```
var cs = new OracleConnectionStringBuilder {
	UserID = "SYSTEM",
	Password = ????,
	DataSource = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)))"
};
var conn = new OracleConnection(cs.ConnectionString);
conn.Open();

var command = conn.CreateCommand();
command.Parameters.Add(new OracleParameter("lockName", OracleDbType.Varchar2) { Value = "test" });
var outputParameter = new OracleParameter("returnCode", OracleDbType.Int32, ParameterDirection.Output);
command.Parameters.Add(outputParameter);
command.CommandText = @"
DECLARE
	lockId VARCHAR2(128);
BEGIN	
	DBMS_LOCK.ALLOCATE_UNIQUE(:lockName, lockId);
	:returnCode := DBMS_LOCK.REQUEST(
		lockId,
		DBMS_LOCK.X_MODE
	);
END;";
command.ExecuteNonQuery();
outputParameter.Value.Dump();
```

**Comment by odin568** [comment]
I am Happy to Support you with Testing, Just Ping me

**Comment by madelson** [comment]
Thanks @odin568 that would be great. It will take me a bit to actually code up the implementation but I'll let you know when a prerelease is available.

In the meantime, if you happen to know how to query for idle sessions (connections that are open but not doing running any commands) in Oracle that would be super helpful; I'll need it for my testing.

**Comment by odin568** [comment]
There are two main global tables which should have the information: gv$session s, v$process
Found [here](https://oracledbwr.com/check-oracle-active-and-inactive-sessions/) a page with good examples. Hoep that helps :-)

**Comment by madelson** [comment]
Thanks @odin568!

Another Oracle question for you: do you typically call `OracleCommand.Prepare()` before executing commands? For some database drivers this is important while for others it isn't.

**Comment by odin568** [comment]
No, you don't need it, does not have any effect, see https://docs.oracle.com/html/E10927_01/OracleCommandClass.htm
`This method is a no-op`
Another source: https://stackoverflow.com/a/33667968

**Comment by madelson** [comment]
Running into issues getting command cancellation to work properly, see https://github.com/oracle/dotnet-db-samples/issues/211

**Comment by odin568** [comment]
Hmm... Is the answer there a Blocker?

**Comment by madelson** [comment]
@odin568 sorry thought I had replied here earlier. No it is not a blocker and I'm continuing to progress with the implementation.

However, this will limit the functionality somewhat. The main thing we lose is the ability to cancel lock requests which is pretty valuable. As a workaround for that, I'm thinking of implementing longer lock requests using a loop with chances to check the cancellation token in between.

**Comment by madelson** [comment]
Update on this:

While I did get oracle working on my machine through docker, I've found the docker-based oracle to be incredibly unreliable. I have to restart the database frequently and constantly encounter issues like connection timeouts. Perhaps there is a fix for this (e. g. some configuration I'm missing). I'd be happy to try things but for now that is blocking further progress.

The other avenue I'm exploring is using oracle cloud's free tier. Unfortunately that is running into issues as well (see https://github.com/oracle/dotnet-db-samples/issues/225).

**Comment by madelson** [comment]
@odin568 I've published a beta release of the Oracle package here: https://www.nuget.org/packages/DistributedLock.Oracle/1.0.0-beta001 . Can you try it out in your environment?

Thanks!

**Comment by odin568** [comment]
Will do this week! Thank you!

**Comment by odin568** [comment]
So first the good thing: On one schema I have on one of our oracles, it works great.

On the same database, different schema, I get 
```
Unhandled exception. Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-06550: line 5, column 21:
PLS-00201: identifier 'SYS.DBMS_LOCK' must be declared
ORA-06550: line 5, column 21:
PL/SQL: Statement ignored
```
I think i would need to grant something like 
```sql
connect as sys
grant execute on SYS.DBMS_LOCK to someuser;
```
The schema where it works is our historic "god" schema. Newer stuff we build more modular and have dedicated schemas with only the rights needed. So probably that is something to resolve on my end, but perhaps a topic for documentation.

So far thanks a lot - will make some more tests but it looks promising!!

**Comment by madelson** [comment]
Thanks for testing @odin568 ! From some quick googling I found https://stackoverflow.com/questions/10870787/oracle-pl-sql-dbms-lock-error which suggests that your solution to the permissions issue is the correct one.

I've added this section to the Oracle docs: https://github.com/madelson/DistributedLock/blob/oracle/docs/DistributedLock.Oracle.md#setup

I'll aim to publish a stable version of the package tomorrow!

**Comment by madelson** [comment]
Released in DistributedLock.Oracle 1.0.0 / DistributedLock 2.3.0
