### ISSUE TITLE
Assembly is not strong-named

### ISSUE THREAD

**Issue by pedropaulovc** [madelson/DistributedLock#47]
**Repro steps:**

1. Download the latest version from NuGet
2. Unpack the `.nupkg` file
3. Run `sn -vf DistributedLock.1.5.0\lib\net45\DistributedLock.dll`

**Expected:**
The `sn.exe` tool would output 

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'DistributedLock.1.5.0\lib\net45\DistributedLock.dll' is valid
```

**Actual:**
The `sn.exe` tool outputs

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

DistributedLock.1.5.0\lib\net45\DistributedLock.dll does not represent a strongly named assembly
```

**Observation:**
This blocks strong-named .NET assemblies from depending on `DistributedLock`. See [Why strong-name your assemblies?](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named#why-strong-name-your-assemblies)

**Comment by maxkoshevoi** [comment]
Hi, could you please release version 1.5.1 that are strongly named. So we don't need to wait and migrate to new version only to get strongly named assembly.

**Comment by pedropaulovc** [comment]
@maxkoshevoi This is what @madelson said in #48 :

> Hi @pedropaulovc thanks for contributing.
> 
> Since adding a strong name to an assembly is a binary breaking change, I won't be able to merge this into the 1.x series.
> 
> I am currently working on the 2.0 version (see the 2.0 branch) which is intended to have strong-named assemblies. Would you consider performing this change on the 2.0 branch and filing a PR against that branch?
> 
> Thanks!

**Comment by madelson** [comment]
@maxkoshevoi the alpha02 versions of releases should be fairly stable (tests are passing, no major further breaking API changes planned) and have strong names.
