### ISSUE TITLE
Where is DistributedLock.WaitHandles (>= 1.0.0-alpha01)

### ISSUE THREAD

**Issue by patrickgalbraith** [madelson/DistributedLock#55]
Installing 2.0 returns the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package DistributedLock.WaitHandles with version (>= 1.0.0-alpha01)
  - Found 1 version(s) in nuget.org [ Nearest version: 0.0.0-alpha000 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
```

**Comment by patrickgalbraith** [comment]
I've managed to get away with just referencing the Azure package directly.

```
<PackageReference Include="DistributedLock.Azure" Version="1.0.0-alpha01" />
```

**Comment by madelson** [comment]
@patrickgalbraith let me know if you need the waithandles alpha and I can publish.

**Comment by patrickgalbraith** [comment]
@madelson No all good. I originally tried to reference the main package but that didn't work. However referencing the Azure package directly worked.

Any idea when the 2.0 branch might be out? It's working well for me so far.

Thanks for all the great work on this project!

**Comment by madelson** [comment]
This should be fixed now with the alpha02 prerelease. Hoping to have the stable release out in the next month or so.
