### ISSUE TITLE
Have you considered make this NuGet working with PostgresSQL? (.NET Core 3.1)

### ISSUE THREAD

**Issue by MazurKamil** [madelson/DistributedLock#56]

**Comment by madelson** [comment]
@MazurKamil yes! Version 2.0 has PostGres support. I haven't released the official version yet (it's a work in progress), but there is a prerelease version that you can download here: https://www.nuget.org/packages/DistributedLock.Postgres/1.0.0-alpha01

Let me know if you have any trouble with that!

**Comment by MazurKamil** [comment]
Thanks for answer , it work perfectly. <3
