### ISSUE TITLE
Remove PDBs for Microsoft.Data.SqlClient.SNI.x64.dll and Microsoft.Data.SqlClient.SNI.x86.dll

### ISSUE THREAD

**Issue by maxkoshevoi** [madelson/DistributedLock#58]
When installing NuGet DistributedLock.SqlServer v1.0.0-alpha01 there are two dll's in the output folder that have PDB files: 
![image](https://user-images.githubusercontent.com/6609929/102762200-a0f1ad00-4380-11eb-8d6c-38461d1db204.png)

Could you please remove those PDB files? Our pipeline that validates artifacts doesn't expect any third-party assembly to have PDB files and fails (since it seems like those PDBs are also invalid):
![image](https://user-images.githubusercontent.com/6609929/102762522-12c9f680-4381-11eb-8336-b35b9d0dbe4c.png)

**Update:**
This issue is with [Microsoft.Data.SqlClient.SNI](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI.runtime/2.1.1)   NuGet itself: https://github.com/dotnet/SqlClient/issues/644#issuecomment-716709017

Could you please update it to version 2.1.1?

**Comment by madelson** [comment]
Hi @maxkoshevoi thanks for reporting!

I've marked this for inclusion in the 2.0 release which I am currently working on.

**Please let me know if you would like me to publish a prerelease version** that includes this change so that you can start consuming it before 2.0 is fully ready.

**Comment by maxkoshevoi** [comment]
It's interesting but updating to 2.1.1 doesn't help. I tried to fork your project and update it and install 2.1.1 into my projects but PDSs are still present. Seems like I'm missing something.

I'm already using `DistributedLock.SqlServer v1.0.0-alpha01` since it's the first version that is strongly typed, so I don't have much chose. Are you saying it's not ready yet? My usecase is `SqlDistributedLock().AcquireAsync()` seems to be working so far. If it's not ready, could you release DistributedLock v1.x.x that is the same as 1.5.0, but strongly typed?

**Comment by madelson** [comment]
> updating to 2.1.1 doesn't help

After you've done this, what does your package.lock.json file look like in the project which is having issues? Can you confirm that 2.1.1 is being resolved? It seems really odd to me that the distributed lock package should be able to affect this in any way.

> I'm already using DistributedLock.SqlServer v1.0.0-alpha01 since it's the first version that is strongly typed, so I don't have much chose. Are you saying it's not ready yet? My usecase is SqlDistributedLock().AcquireAsync() seems to be working so far. If it's not ready, could you release DistributedLock v1.x.x that is the same as 1.5.0, but strongly typed?

I do hope to have a stable release ready in the not-too-distant future but until then I will try to push out an updated alpha with the higher version bound. Note that I can't add strong naming to 1.x because changing to strong named is a binary breaking change.

**Comment by madelson** [comment]
@maxkoshevoi FYI I've pushed out a new prerelease version which references the updated sqlclient: https://www.nuget.org/packages/distributedlock.sqlserver/1.0.0-alpha02

**Comment by maxkoshevoi** [comment]
Thank you for alpha2. Yes, the problem is with Microsoft.Data.SqlClient package, not with this one. I think issue in this repository can be closed
