### ISSUE TITLE
How can I mock IDistributedLockProvider method AcquireLockAsync in XUnit Unit Test?

### ISSUE THREAD

**Issue by grahamauty** [madelson/DistributedLock#63]
From .NET Core 3.1 projects, I'm using the following to create a singleton in the dependency injection container:

```
var blobContainerClient = new BlobContainerClient(storageConnectionString, locksContainerName);

builder.Services.AddSingleton<IDistributedLockProvider, AzureBlobLeaseDistributedSynchronizationProvider>((provider) =>
    new AzureBlobLeaseDistributedSynchronizationProvider(blobContainerClient)
);
```

I'm then injecting this into my target class's private field like so:

`private readonly IDistributedLockProvider _distributedLockProvider;`

My class then uses code such as this to utilize the Distributed Lock:

```
using (await _distributedLockProvider.AcquireLockAsync(lockName)) {
    // stuff to be protected ...
}
```

My question is, how can I mock the call to AcquireLockAsync in my Moq powered XUnit unit test? The problem I have is that this method is an extension method, and Moq is unable to mock it. Is there an alternative means of doing this and do you have any examples? Note that the unit tests must pass as part of the CI build pipeline on Azure DevOps, so using the storage emulator is not really an option, and besides, that would make it not a real unit test.

For the moment I've had to remove the unit tests, but I'd like to reinstate them as soon as I can, if there's a viable solution.

Thanks
Graham

**Comment by madelson** [comment]
@grahamauty yep you can't mock the extension directly. However, the extension is just 2 calls: CreateLock + AcquireAsync. So, you can just mock CreateLock() to return a lock whose AcquireAsync method does what you'd want it to do. Does that make sense?

**Comment by grahamauty** [comment]
Thanks @madelson, you've pointed me in the right direction. I have the following which now gives me a working unit test:

```
    private readonly Mock<IDistributedLockProvider> _mockDistributedLockProvider;
    ....
    public SutComponentTests() {
        _mockDistributedLockProvider = new Mock<IDistributedLockProvider>();
        _sut = new SutComponent(_mockDistributedLockProvider.Object);
    }

    [Fact]
    public async Task TestMethod() {
       _mockDistributedLockProvider.Setup(r => r.CreateLock(
                It.IsAny<string>()))
            .Returns(new MockDistributedLock());

        var result = await _sut.MethodUnderTest();

        // Assert ...
    }
```

where `MockDistributedLock` is defined as:

```
    internal class MockDistributedLock : IDistributedLock {
        public string Name => throw new NotImplementedException();

        public IDistributedSynchronizationHandle Acquire(TimeSpan? timeout = null, CancellationToken cancellationToken = default) {
            throw new NotImplementedException();
        }

        public ValueTask<IDistributedSynchronizationHandle> AcquireAsync(TimeSpan? timeout = null, CancellationToken cancellationToken = default) {
            // THE IMPORTANT BIT
            return new ValueTask<IDistributedSynchronizationHandle>();
        }

        public IDistributedSynchronizationHandle TryAcquire(TimeSpan timeout = default, CancellationToken cancellationToken = default) {
            throw new NotImplementedException();
        }

        public ValueTask<IDistributedSynchronizationHandle> TryAcquireAsync(TimeSpan timeout = default, CancellationToken cancellationToken = default) {
            throw new NotImplementedException();
        }
    }
```

**Comment by madelson** [comment]
In the future if we implement https://github.com/madelson/DistributedLock/issues/38, this might become even easier; you could use an in-memory lock as a fairly-realistic mock.

**Comment by PatriQ94** [comment]
Hello, I'm having the exact same issue but with ``TryAcquireLockAsync``. I've used the exact example given by @grahamauty but changed the return type of the method like so:
```
public ValueTask<IDistributedSynchronizationHandle> TryAcquireAsync(TimeSpan timeout = default, CancellationToken cancellationToken = default) {
         return new ValueTask<IDistributedSynchronizationHandle>();
}
```
After this change, the code doesn't throw errors anymore, but upon calling the method in all my services like so:
`` await using var handle = await _synchronizationProvider.TryAcquireLockAsync(lockKey);``
the handle is always null. What do I need to change for it to return anything but null?

**Comment by madelson** [comment]
@PatriQ94 TryAcquire methods return null if the acquire attempt fails. If you want to faithfully mock a lock instance you’ll need to make your mock behave like a real instance.

Rather than creating your own mock implementation, I would suggest using something like FileDistributedLock in your tests: this gives realistic behavior without any dependency on an external db.

**Comment by userAXC001** [comment]
@PatriQ94 If it's of any help, I was able to get a running test with the code below.  I wouldn't consider it a clean solution but it gets the job done

```
[Fact]
public async Task TestMethod()
{
	//Arrange
	var _fixture = new Fixture().Customize(new AutoMoqCustomization());
	var distributedSynchronizationHandleMock = new Mock<IDistributedSynchronizationHandle>();
	var lockMock = new Mock<IDistributedLock>();
	lockMock.Setup(x => x.TryAcquireAsync(It.IsAny<TimeSpan>(), It.IsAny<CancellationToken>()))
		.ReturnsAsync(distributedSynchronizationHandleMock.Object);
	var lockProviderMock = _fixture.Freeze<Mock<IDistributedLockProvider>>();
	lockProviderMock.Setup(r => r.CreateLock(It.IsAny<string>()))
		.Returns((new Mock<IDistributedLock>()).Object);

	var sut = _fixture.Create<SutComponent>();

	//Act
	var result = await _sut.MethodUnderTest();

	//Assert ...
}
```
