### ISSUE TITLE
Question: Test lock without granting

### ISSUE THREAD

**Issue by Ericinator** [madelson/DistributedLock#72]
Is there any way to test whether a lock can be acquired without actually acquiring it? Similar to Sql Server APPLOCK_TEST?
An example use case is where there is a long running task that may not overlap with other smaller tasks, but those smaller tasks are allowed to overlap.

**Comment by madelson** [comment]
Hi @Ericinator thanks for reaching out. Two initial questions/thoughts:

(1) What provider are you using (SQL Server?)?

(2) Based on your description `a long running task that may not overlap with other smaller tasks, but those smaller tasks are allowed to overlap`, I'm wondering whether a `ReaderWriterLock` applies to your use-case. The small tasks would take read locks and the larger task would take the write lock. That would guarantee that at any given time either any number of small tasks would be running OR exactly one large task would be running.

**Comment by Ericinator** [comment]
Hi @madelson thanks for the quick response!

1) Yes SQL Server

2) I had a quick read through the docs and the code and I think you are right. I will close the ticket and open a new one if it turns out that we need something else, but it looks promising enough. 

Thanks for the help! 

P.S. Thanks for the library.
