### ISSUE TITLE
FileSystem lock with Azure WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by bgiot** [madelson/DistributedLock#74]
Hi, it's more a question: what whould be the best configuration for locks location when using WEBSITE_RUN_FROM_PACKAGE feature in Azure Web App ?  ContentRoot seems not to be an option...

**Comment by madelson** [comment]
@bgiot can you explain what scope you want the lock to have? Also, what issues are you having and what have you tried?

**Comment by bgiot** [comment]
@madelson  You can deploy a webapp in Azure App Service under the WAR/ZIP format - so a readonly package. But if we still want to use the FileSystem lock, it doesn't work because the location of the app (the zip file) is read-only. What would be the best practice to configure the FileSystem lock location in this case?

**Comment by madelson** [comment]
@bgiot I'm not familiar with that exact scenario but I would guess that you could still use something like the temp directory for file-based locking. However, you need to keep in mind that the scope of a file-based lock is based on where the file actually sits; if you are trying to coordinate between different machines in Azure that have different file systems, it's not going to work and in that case you're better off choosing a different lock type.
