### ISSUE TITLE
SqlDistributedLock fails with connection string randomly.

### ISSUE THREAD

**Issue by Sophtware-com** [madelson/DistributedLock#79]
When using SqlDistributedLock with a valid connection string, TryAcquireAsync will fail to connect to the database saying the login failed randomly.

**Comment by madelson** [comment]
@Sophtware-com thanks for reporting an issue. Can you please provide:

* The version of the library you are using
* A code snippet showing how you construct the lock and how you acquire it (e. g. what options you are using)
* The full `ToString` of the exception

**Comment by Sophtware-com** [comment]
Sorry, I wanted to give you this information, but my company made me pull the NuGet from our project. I actually think the password was being left off the connection string. So it was probably not an issue with your library. Thanks for the quick response!

**Comment by madelson** [comment]
Thanks for the update @Sophtware-com 

> my company made me pull the NuGet from our project

Just out of curiosity, was this due to any perceived issue with the library itself or merely corporate policy?

**Comment by Sophtware-com** [comment]
Due to the perceived issue unfortunately.

Kind Regards,
Michael Lange - K4MDL
