### ISSUE TITLE
Is there a schedule to support MySQL?

### ISSUE THREAD

**Issue by theplacefordev** [madelson/DistributedLock#95]
Thank you for the great library! Do you consider to support MySQL? It does support locking features https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html to implement distributed locking on top of it.

Thanks in advance.
Rustam

**Comment by theplacefordev** [comment]
#24

**Comment by madelson** [comment]
@theplacefordev I'd be open to adding this; seems straightforward. Would you be willing to test out a prerelease package and confirm that it is functioning as expected?

**Comment by theplacefordev** [comment]
@madelson yes, of course. Thanks in advance!

**Comment by madelson** [comment]
@theplacefordev as I've started working on this I noticed that there seem to be 2 popular drivers: https://www.nuget.org/packages/MySql.Data/ and https://www.nuget.org/packages/MySqlConnector/. 

I'm curious which of these you have experience with and whether you think one or the other seems like a better default?

**Comment by madelson** [comment]
Actually, seems like we'll have to use MySqlConnector as the default because it has better license terms.

**Comment by theplacefordev** [comment]
@madelson I use it with EF Core and Pomelo.EntityFrameworkCore.MySql provider which is using MySqlConnector, so it works for me

**Comment by madelson** [comment]
Thanks @theplacefordev ! I am close to having an alpha package out.

**Comment by madelson** [comment]
@theplacefordev I've published a release candidate version: https://www.nuget.org/packages/DistributedLock.MySql/1.0.0-rc01

Would you mind giving it a try and confirming that it works for you?

**Comment by theplacefordev** [comment]
@madelson sure I will try it tomorrow. Thanks a lot!

**Comment by bgrainger** [comment]
FYI, MySqlConnector is the only MySQL ADO.NET library that supports asynchronous operations; all "Async" methods in MySql.Data operate synchronously: https://bugs.mysql.com/bug.php?id=70111.

**Comment by madelson** [comment]
@theplacefordev not rush but did you get a chance to try this library?

**Comment by theplacefordev** [comment]
@madelson Sorry for the delay. I've tested it on my laptop with MySql 5.7, .NET Core 3.1, EF 5, and MySqlConnector 1.3.11 - it seems to works for my test cases. Thank you!

**Comment by madelson** [comment]
Thanks! I'll get a stable version merged soon! Re-opening for now to remind me.
